var SMILES = {
    main: {
        ':mellow:':'noexpression.gif',
        ':huh:':'wassat.gif',
        '^_^':'happy.gif',
        ':o':'shocked.gif',
        ';)':'wink.gif',
        ':P':'tongue.gif',
        ':D':'biggrin.gif',
        ':lol:':'laughing.gif',
        ':cool:':'cool.gif',
        ':rolleyes:':'rolleyes.gif',
        '-_-':'sleeping.gif',
        '&lt;_&lt;':'getlost.gif',
        ':wub:':'wub.gif',
        '&gt;:(':'abuse.gif',
        ':angry:':'angry.gif',
        ':(':'sad.gif',
        ':unsure:':'unsure.gif',
        ':wacko:':'wacko.gif',
        ':blink:':'blink.gif',
        ':ph34r:':'fear.gif',
        '(!)':'excl.gif',
        ':shifty:':'shifty.gif',
        ':x':'sick.gif',
        ":'(":'crying.gif',
        ':alien:':'alien.gif',
        '(w00t)':'w00t.gif',
        '&gt;_&lt;':'pinch.gif',
        'o:)':'innocent.gif',
        ':blush:':'blushing.gif',
        ':*':'kiss.gif',
        ':ermm:':'ermm.gif',
        ':devil:':'devil.gif',
        ':luck:':'clover.gif',
        ':nuke:':'nuke.gif',
        ':pirate:':'chris.gif',
        ':flowers:':'flowers.gif',
        ':teehee:':'stuart.gif',
        ':drink:':'drink.gif',
        ':whistle:':'whistling.gif',
        ':sweating:':'sweatingbullets.gif',
        ':thumbsup:':'thumbsup.gif',        
        ':beer:':'beer.gif',
        ':%:':'dance.gif',
        ':kiya:':'kiya.gif',
        ':handshake:':'handshake.gif',
        ':good:':'good.gif',
        ':bad:':'bad.gif',
        ':coffee:':'coffee.gif',
        ':)':'original.gif'
    },
    hidden: {
        ':elf:':'elf.png',
        ':diablo:':'diablo.gif',
        ':friday:':'friday.gif',

        // Aliases:
        ':Р':'tongue.gif',
        ':В':'biggrin.gif'
    }
};

